// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMPtY7H3txsAzpRZji2wU1W4nL_kkSOM',
    appId: '1:588604767486:web:e39e40c2ed013bf710b9af',
    messagingSenderId: '588604767486',
    projectId: 'e-riksha-84f36',
    authDomain: 'e-riksha-84f36.firebaseapp.com',
    storageBucket: 'e-riksha-84f36.firebasestorage.app',
    measurementId: 'G-HK922EF7XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMcYRX8ZCaYriAa09VASbCy0IeE9UEk5E',
    appId: '1:588604767486:android:b4768473cb8f283810b9af',
    messagingSenderId: '588604767486',
    projectId: 'e-riksha-84f36',
    storageBucket: 'e-riksha-84f36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAy6lulGUUWs5zGubSKh7xYv3TqjzARAU',
    appId: '1:588604767486:ios:5bef5a2ad168198b10b9af',
    messagingSenderId: '588604767486',
    projectId: 'e-riksha-84f36',
    storageBucket: 'e-riksha-84f36.firebasestorage.app',
    iosBundleId: 'com.example.eRiksha',
  );
}
